/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.cs.test.events.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Events service. Represents a row in the &quot;CS_Events&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.cs.test.events.model.impl.EventsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.cs.test.events.model.impl.EventsImpl</code>.
 * </p>
 *
 * @author Liferay CS
 * @see Events
 * @generated
 */
@ProviderType
public interface EventsModel
	extends BaseModel<Events>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a events model instance should use the {@link Events} interface instead.
	 */

	/**
	 * Returns the primary key of this events.
	 *
	 * @return the primary key of this events
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this events.
	 *
	 * @param primaryKey the primary key of this events
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this events.
	 *
	 * @return the uuid of this events
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this events.
	 *
	 * @param uuid the uuid of this events
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the event ID of this events.
	 *
	 * @return the event ID of this events
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this events.
	 *
	 * @param eventId the event ID of this events
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the group ID of this events.
	 *
	 * @return the group ID of this events
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this events.
	 *
	 * @param groupId the group ID of this events
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this events.
	 *
	 * @return the company ID of this events
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this events.
	 *
	 * @param companyId the company ID of this events
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this events.
	 *
	 * @return the user ID of this events
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this events.
	 *
	 * @param userId the user ID of this events
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this events.
	 *
	 * @return the user uuid of this events
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this events.
	 *
	 * @param userUuid the user uuid of this events
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this events.
	 *
	 * @return the user name of this events
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this events.
	 *
	 * @param userName the user name of this events
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this events.
	 *
	 * @return the create date of this events
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this events.
	 *
	 * @param createDate the create date of this events
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this events.
	 *
	 * @return the modified date of this events
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this events.
	 *
	 * @param modifiedDate the modified date of this events
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this events.
	 *
	 * @return the name of this events
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this events.
	 *
	 * @param name the name of this events
	 */
	public void setName(String name);

	/**
	 * Returns the description of this events.
	 *
	 * @return the description of this events
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this events.
	 *
	 * @param description the description of this events
	 */
	public void setDescription(String description);

	/**
	 * Returns the department of this events.
	 *
	 * @return the department of this events
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this events.
	 *
	 * @param department the department of this events
	 */
	public void setDepartment(String department);

	/**
	 * Returns the visibility of this events.
	 *
	 * @return the visibility of this events
	 */
	public int getVisibility();

	/**
	 * Sets the visibility of this events.
	 *
	 * @param visibility the visibility of this events
	 */
	public void setVisibility(int visibility);

	/**
	 * Returns the max count of this events.
	 *
	 * @return the max count of this events
	 */
	public int getMaxCount();

	/**
	 * Sets the max count of this events.
	 *
	 * @param maxCount the max count of this events
	 */
	public void setMaxCount(int maxCount);

	/**
	 * Returns the start date of this events.
	 *
	 * @return the start date of this events
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this events.
	 *
	 * @param startDate the start date of this events
	 */
	public void setStartDate(Date startDate);

	@Override
	public Events cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}